FROM node:22-alpine as deps

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev


FROM node:22-alpine

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY package*.json ./
COPY src ./src

RUN mkdir -p uploads
EXPOSE 5000


CMD ["node","src/server.js"]